environments:
  - name: base
    title: Base Configuration Options
    description: Basic configuration options needed for all OVB environments
    files:
      templates/quintupleo.yaml:
        parameters:
          - bmc_flavor
          - bmc_image
          - baremetal_flavor
          - baremetal_image
          - key_name
          - private_net
          - bmc_prefix
          - baremetal_prefix
          - node_count
          - undercloud_name
          - undercloud_image
          - undercloud_flavor
          - external_net
          - role
      templates/undercloud-networks.yaml:
        parameters:
          - public_net
          - public_net_shared
          - provision_net
          - provision_net_shared
    sample_values:
      baremetal_image: ipxe-boot
  -
    name: base-role
    title: Base Configuration Options for Secondary Roles
    description: |
      Configuration options that need to be set when deploying an OVB
      environment that has multiple roles.
    files:
      templates/quintupleo.yaml:
        parameters:
          - baremetal_flavor
          - key_name
          - node_count
          - role
    sample_values:
      role: compute
  -
    name: base-extra-node
    title: Base Configuration Options for Extra Nodes
    description: |
      Configuration options that need to be set when deploying an OVB
      environment with extra undercloud-like nodes.  This environment
      should be used like a role file, but will deploy an undercloud-like
      node instead of more baremetal nodes.
    files:
      templates/quintupleo.yaml:
        parameters:
          - baremetal_flavor
          - baremetal_image
          - key_name
          - node_count
          - role
    sample_values:
      role: extra
      baremetal_image: CentOS-7-x86_64-GenericCloud
      node_count: 1
    resource_registry:
      OS::OVB::BaremetalPorts: ../templates/baremetal-ports-extra-node.yaml
  -
    name: all-networks
    title: Deploy with All Networks Enabled
    description: |
      Deploy an OVB stack that adds interfaces for all the standard TripleO
      network isolation networks.
    files:
      templates/baremetal-networks-all.yaml:
        parameters: all
    resource_registry:
      OS::OVB::BaremetalNetworks: ../templates/baremetal-networks-all.yaml
      OS::OVB::BaremetalPorts: ../templates/baremetal-ports-all.yaml
    children:
      -
        name: all-networks-public-bond
        title: Deploy with All Networks Enabled and Two Public Interfaces
        description: |
          Deploy an OVB stack that adds interfaces for all the standard TripleO
          network isolation networks.  This version will deploy duplicate
          public network interfaces on the baremetal instances so that the
          public network can be configured as a bond.
        resource_registry:
          OS::OVB::BaremetalNetworks: ../templates/baremetal-networks-all.yaml
          OS::OVB::BaremetalPorts: ../templates/baremetal-ports-public-bond.yaml
  -
    name: create-private-network
    title: Create a Private Network
    description: |
      Create the private network as part of the OVB stack instead of using an
      existing one.
    files:
      templates/private-net-create.yaml:
        parameters:
          - dns_nameservers
          - private_net_cidr
    resource_registry:
      OS::OVB::PrivateNetwork: ../templates/private-net-create.yaml
  -
    name: quintupleo-no-undercloud
    title: Disable the Undercloud in a QuintupleO Stack
    description: |
      Deploy a QuintupleO environment, but do not create the undercloud
      instance.
    files: {}
    resource_registry:
      OS::OVB::UndercloudEnvironment: OS::Heat::None
  -
    name: undercloud-floating-none
    title: Do Not Assign a Floating IP to the Undercloud
    description: |
      When deploying the undercloud, do not assign a floating ip to it.
    files: {}
    resource_registry:
      OS::OVB::UndercloudFloating: ../templates/undercloud-floating-none.yaml
  -
    name: undercloud-floating-existing
    title: Assign the Undercloud an Existing Floating IP
    description: |
      When deploying the undercloud, assign it an existing floating IP instead
      of creating a new one.
    files:
      templates/undercloud-floating-existing.yaml:
        parameters:
          - undercloud_floating_ip
          - undercloud_floating_ip_id
    resource_registry:
      OS::OVB::UndercloudFloating: ../templates/undercloud-floating-existing.yaml
  -
    name: boot-from-volume
    title: Boot Undercloud and Baremetal Instances from Volume
    description: |
      Boot the undercloud and baremetal instances from Cinder volumes instead of
      ephemeral storage.
    files:
      templates/undercloud-volume.yaml:
        parameters:
          - undercloud_volume_size
      templates/virtual-baremetal-servers-volume.yaml:
        parameters:
          - baremetal_volume_size
    resource_registry:
      OS::OVB::UndercloudEnvironment: ../templates/undercloud-volume.yaml
      OS::OVB::ServerPair: ../templates/virtual-baremetal-servers-volume.yaml
  -
    name: boot-baremetal-from-volume
    title: Boot Baremetal Instances from Volume
    description: |
      Boot the baremetal instances from Cinder volumes instead of
      ephemeral storage.
    files:
      templates/virtual-baremetal-servers-volume.yaml:
        parameters:
          - baremetal_volume_size
    resource_registry:
      OS::OVB::ServerPair: ../templates/virtual-baremetal-servers-volume.yaml
  -
    name: boot-undercloud-from-volume
    title: Boot Undercloud Instance from Volume
    description: |
      Boot the undercloud instance from a Cinder volume instead of
      ephemeral storage.
    files:
      templates/undercloud-volume.yaml:
        parameters:
          - undercloud_volume_size
    resource_registry:
      OS::OVB::UndercloudEnvironment: ../templates/undercloud-volume.yaml
  -
    name: bmc-use-cache
    title: Enable Instance Status Caching in BMC
    description: |
      Enable caching of instance status in the BMC.  This should reduce load on
      the host cloud, but at the cost of potential inconsistency if the state
      of a baremetal instance is changed without using the BMC.
    files:
      templates/virtual-baremetal.yaml:
        parameters:
          - bmc_use_cache
    sample_values:
      bmc_use_cache: True
  -
    name: routed-networks-configuration
    title: Configuration for Routed Networks
    description: |
      Contains the available parameters that need to be configured when using
      a routed networks environment. Requires the routed-networks.yaml
      environment.
    files:
      templates/dhcp-relay.yaml:
        parameters:
          - dhcp_relay_flavor
          - dhcp_relay_image
  -
    name: routed-networks
    title: Enable Routed Networks
    description: |
      Enable use of routed networks, where there may be multiple separate
      networks connected with a router and DHCP relay. Do not pass any other
      network configuration environments after this one or they may override
      the changes made by this environment. When this environment is in use,
      the routed-networks-configuration environment should usually be
      included as well.
    resource_registry:
      OS::OVB::UndercloudNetworks: ../templates/undercloud-networks-routed.yaml
      OS::OVB::BaremetalNetworks: ../templates/baremetal-networks-routed.yaml
      OS::OVB::DHCPRelay: ../templates/dhcp-relay.yaml
  -
    name: routed-networks-role
    title: Base Role Configuration for Routed Networks
    description: |
      A base role environment that contains the necessary parameters for
      deploying with routed networks.
    files:
      templates/quintupleo.yaml:
        parameters:
          - baremetal_flavor
          - key_name
          - node_count
          - role
      templates/undercloud-networks.yaml:
        parameters:
          - provision_net
      templates/baremetal-networks-all.yaml:
        parameters:
          - overcloud_internal_net
          - overcloud_storage_net
          - overcloud_storage_mgmt_net
          - overcloud_tenant_net
    sample_values:
      role: leaf1
      provision_net: provision2
      overcloud_internal_net: overcloud_internal2
      overcloud_storage_net: overcloud_storage2
      overcloud_storage_mgmt_net: overcloud_storage_mgmt2
      overcloud_tenant_net: overcloud_tenant2
  -
    name: public-router
    title: Public Network External Router
    description: |
      Deploy a router that connects the public and external networks. This
      allows the public network to be used as a gateway instead of routing all
      traffic through the undercloud.
    resource_registry:
      OS::OVB::UndercloudNetworks: ../templates/undercloud-networks-public-router.yaml

