# *******************************************************************
# This file was created automatically by the sample environment
# generator. Developers should use `tox -e genconfig` to update it.
# Users are recommended to make changes to a copy of the file instead
# of the original, if any customizations are needed.
# *******************************************************************
# title: Deploy with All Networks Enabled
# description: |
#   Deploy an OVB stack that adds interfaces for all the standard TripleO
#   network isolation networks.  This version uses the port-security
#   Neutron extension to allow OVB to be run on clouds with security
#   groups enabled.
parameter_defaults:
  # Name of internal API network
  # Type: string
  overcloud_internal_net: overcloud_internal

  # CIDR for internal API network subnet.  This is typically irrelevant and
  # does not need to be changed.
  # Type: string
  overcloud_internal_net_cidr: 172.17.0.0/24

  # Name of storage management network
  # Type: string
  overcloud_storage_mgmt_net: overcloud_storage_mgmt

  # CIDR for storage management network subnet.  This is typically irrelevant
  # and does not need to be changed.
  # Type: string
  overcloud_storage_mgmt_net_cidr: 172.19.0.0/24

  # Name of storage network
  # Type: string
  overcloud_storage_net: overcloud_storage

  # CIDR for storage network subnet.  This is typically irrelevant and
  # does not need to be changed.
  # Type: string
  overcloud_storage_net_cidr: 172.18.0.0/24

  # Name of tenant network
  # Type: string
  overcloud_tenant_net: overcloud_tenant

  # CIDR for tenant network subnet.  This is typically irrelevant and
  # does not need to be changed.
  # Type: string
  overcloud_tenant_net_cidr: 172.16.0.0/24

resource_registry:
  OS::OVB::BMCPort: ../templates/bmc-port-port-security.yaml
  OS::OVB::BaremetalNetworks: ../templates/baremetal-networks-all.yaml
  OS::OVB::BaremetalPorts: ../templates/baremetal-ports-all-port-security.yaml
  OS::OVB::UndercloudPorts: ../templates/undercloud-ports-port-security.yaml
