heat_template_version: 2015-10-15

parameters:

  undercloud_name:
    type: string

  private_net:
    type: string

  provision_net:
    type: string

  public_net:
    type: string

resources:
  undercloud_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        list_join:
        - '_'
        - - {get_param: undercloud_name}
          - 'sg'
      description: Ping and SSH
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22

  private_undercloud_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - '_'
        - - {get_param: undercloud_name}
          - 'private'
      network: {get_param: private_net}
      security_groups:
      - {get_resource: undercloud_sg}

  provision_undercloud_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - '_'
        - - {get_param: undercloud_name}
          - 'provision'
      network: {get_param: provision_net}
      port_security_enabled: False

  public_undercloud_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - '_'
        - - {get_param: undercloud_name}
          - 'public'
      network: {get_param: public_net}
      port_security_enabled: False

outputs:
  ports:
    value:
    - {port: {get_resource: private_undercloud_port}}
    - {port: {get_resource: provision_undercloud_port}}
    - {port: {get_resource: public_undercloud_port}}
